
[target.x86_64-unknown-linux-gnu]
dockerfile = "Dockerfile"

[target.aarch64-unknown-linux-gnu]
dockerfile = "Dockerfile"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "Dockerfile"

[target.riscv64gc-unknown-linux-gnu]
dockerfile = "Dockerfile"

