#!/bin/bash
set -e

TARGET=$CARGO_BUILD_TARGET
CARCH=${TARGET//-*}

cross build --features generate --target=${TARGET} --release --locked --target-dir target
scripts/mkmo locale/
mv target/**/release/paru ./
strip paru
tar --zstd -cf paru-${CARCH}.tar.zst man completions paru.conf locale paru

